import logging
from argparse import ArgumentParser, Namespace
from datetime import datetime

from ipl2py import __version__
from ipl2py.compiler import compile
from ipl2py.utils import get_test_tree

logger = logging.getLogger(__name__)


def read_file(infile: str) -> str:
    try:
        with open(infile, encoding="utf-8") as fin:
            content = fin.read()
    except UnicodeDecodeError:
        logger.exception("Expected %s to be utf-8", infile)
        raise
    return content


def parse_args() -> Namespace:
    parser = ArgumentParser(
        prog="ipl2py",
        description="Source-to-source compiler, from  RMS IPL scripts to Python",
    )
    parser.add_argument(
        "--version",
        help="Print the version number",
        action="version",
        version=__version__,
    )
    parser.add_argument(
        "infile",
        nargs="?",  # Make it optional
        help=("The IPL file to be converted to Python"),
    )
    parser.add_argument(
        "-c",
        "--code",
        type=str,
        dest="code",
        help=(
            "Supply IPL code and print its parse tree. Can "
            "be used with `-p` to pretty print the structure. "
        ),
    )
    parser.add_argument(
        "-d",
        "--debug",
        help="Print debugging information",
        action="store_const",
        dest="loglevel",
        const=logging.DEBUG,
        default=logging.WARNING,
    )
    parser.add_argument(
        "--no-comments",
        action="store_true",
        dest="no_comments",
        help="Discard comments from the IPL script.",
        default=False,
    )
    parser.add_argument(
        "-o",
        "--outfile",
        type=str,
        dest="outfile",
        help="Output Python filepath. Defaults to the same name as the IPL script.",
    )
    parser.add_argument(
        "--ast",
        action="store_true",
        dest="print_ast",
        help="Print the AST",
        default=False,
    )
    parser.add_argument(
        "--parse-tree",
        action="store_true",
        dest="print_parse_tree",
        help="Print the parse tree",
        default=False,
    )
    parser.add_argument(
        "-p",
        "--pretty",
        action="store_true",
        dest="pretty",
        help="Pretty print any trees that are printed",
        default=False,
    )
    parser.add_argument(
        "-v",
        "--verbose",
        help="Be verbose",
        action="store_const",
        dest="loglevel",
        const=logging.INFO,
    )
    args = parser.parse_args()
    return args


def main() -> None:
    args = parse_args()
    logging.basicConfig(level=args.loglevel)

    if args.code:
        content = args.code
    elif args.infile:
        content = read_file(args.infile)
    else:
        content = get_test_tree()

    code = compile(
        content,
        include_comments=False if args.no_comments else True,
        print_parse_tree=args.print_parse_tree,
        print_ast=args.print_ast,
        pretty=args.pretty,
    )

    print(f"# Generated by ipl2py v{__version__} {datetime.now()}")
    print(code)


if __name__ == "__main__":
    main()
